### ISSUE TITLE
about training ferr

### ISSUE THREAD

**Issue by tornadomeet** [tqchen/mxnet-gan#7]
Hello, i trained `gan_mnist.py` with 100 epoch using the defaulted parameters, the ferr value is near `0.015`, which is far from `0.5`, does this mean the generator G is not learned well? 
but the data generated by G seems well like this:
![gen_mnist](https://cloud.githubusercontent.com/assets/5860892/25221640/6ecd1e2c-25e8-11e7-8763-343f340c040a.png)
@tqchen is this normal?

add:
when change the noise input from gaussian to uniform, the `ferr` value is almost the same.

**Comment by tqchen** [comment]
It is normal, usually it is hard to get a balanced gan loss between the two

**Comment by tornadomeet** [comment]
thanks, got it!
